[ ( Name ["list","selected"],     Val { fg = Red,    bg = Def,    styles = [] } )
, ( Name ["edit"],                Val { fg = Black,  bg = White,  styles = [] } )
, ( Name ["edit","focused"],      Val { fg = White,  bg = Blue,   styles = [] } )
, ( Name ["dialog"],              Val { fg = White,  bg = Blue,   styles = [] } )
, ( Name ["button"],              Val { fg = Black,  bg = White,  styles = [] } )
, ( Name ["button","selected"],   Val { fg = Def,    bg = Yellow, styles = [] } )
, ( Name ["progressComplete"],    Val { fg = White,  bg = Blue,   styles = [] } )
, ( Name ["kpxhs","key"],         Val { fg = Def,    bg = White,  styles = [] } )
, ( Name ["kpxhs","label"],       Val { fg = Black,  bg = Def,    styles = [] } )
, ( Name ["kpxhs","line_number"], Val { fg = Yellow, bg = Def,    styles = [] } )
]
