[ (AttrName ["list","selected"],   Fg (ISO 1))
, (AttrName ["edit"],              On (ISO 0) (ISO 7))
, (AttrName ["edit","focused"],    On (ISO 7) (ISO 4))
, (AttrName ["dialog"],            On (ISO 7) (ISO 4))
, (AttrName ["button"],            On (ISO 0) (ISO 7))
, (AttrName ["button","selected"], Bg (ISO 3))
, (AttrName ["kpxhs", "key"],      Bg (ISO 7))
, (AttrName ["kpxhs", "label"],    Fg (ISO 0))
, (AttrName ["progressComplete"],  On (ISO 7) (ISO 4))
]
