[ (["edit"],                          Val { fg = Black,  bg = White,  styles = [] })
, (["edit","focused"],                Val { fg = White,  bg = Blue,   styles = [] })
, (["dialog"],                        Val { fg = White,  bg = Blue,   styles = [] })
, (["button"],                        Val { fg = Black,  bg = White,  styles = [] })
, (["button","selected"],             Val { fg = Def,    bg = Yellow, styles = [] })
, (["progressComplete"],              Val { fg = White,  bg = Blue,   styles = [] })
, (["kpxhs","key"],                   Val { fg = Def,    bg = White,  styles = [] })
, (["kpxhs","label"],                 Val { fg = Black,  bg = Def,    styles = [] })
, (["kpxhs","line_number"],           Val { fg = Yellow, bg = Def,    styles = [] })
, (["kpxhs","list_border"],           Val { fg = Black,  bg = Def,    styles = [] })
, (["kpxhs","list_border","focused"], Val { fg = Blue,   bg = Def,    styles = [] })
, (["kpxhs","directory"],             Val { fg = Black,  bg = Def,    styles = [Bold]})
, (["kpxhs","directory","focused"],   Val { fg = Red,    bg = Def,    styles = [Bold]})
, (["kpxhs","entry"],                 Val { fg = Black,  bg = Def,    styles = [] } )
, (["kpxhs","entry","focused"],       Val { fg = Red,    bg = Def,    styles = [] } )
]
