name: master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            experimental: false
            asset_name: kpxhs-linux-amd64
          - os: macos-latest
            experimental: true
            asset_name: kpxhs-macos-amd64

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: stack install
    - name: Copy binary and rename
      run: |
        mkdir dist
        cp ~/.local/bin/kpxhs dist
        mv dist/kpxhs dist/${{ matrix.asset_name }}_${{ github.sha }}
    - uses: ncipollo/release-action@v1
      with:
        artifacts: dist/${{ matrix.asset_name }}_${{ github.sha }}
        name: master_${{ github.sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.sha }}
