name: master

on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
      - test/*
      - pics/*
      - LICENSE
      - Theming.md

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: kpxhs-linux
          - os: macos-latest
            asset_name: kpxhs-macos

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run hlint
      continue-on-error: true
      run: |
        curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s src/kpxhs
    - name: Build
      run: make build
