name: release

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: kpxhs-linux-amd64
          - os: macos-latest
            asset_name: kpxhs-macos-amd64

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: stack install
    - name: Copy binary and rename
      run: |
        mkdir dist
        cp ~/.local/bin/kpxhs dist
        mv dist/kpxhs dist/${{ matrix.asset_name }}_${{ github.tag }}
    - uses: ncipollo/release-action@v1
      with:
        artifacts: dist/${{ matrix.asset_name }}_${{ github.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
