name: release

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: kpxhs-linux
          - os: macos-latest
            asset_name: kpxhs-macos

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install pandoc
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update
          sudo apt-get install pandoc
        else
          brew update
          brew install pandoc
        fi
    - name: Build docs
      run: |
        cd docs
        make
    - name: Build binary
      run: make install
    - name: Copy binary and rename
      run: |
        mkdir dist
        cp ~/.local/bin/kpxhs dist
        mv dist/kpxhs dist/${{ matrix.asset_name }}
    - name: Generate digest
      run: |
        name=${{ matrix.asset_name }}
        cd dist
        sha256sum "$name" > "${name}.DIGEST"
    - uses: ncipollo/release-action@v1
      with:
        artifacts:
          - dist/${{ matrix.asset_name }}
          - dist/${{ matrix.asset_name }}.DIGEST
          - docs/kpxhs.1
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
